name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev
    - name: config
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: cmake --build build
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: engine-linux
        path: build/engine